INSERT INTO USERS (USERNAME, PASSWORD, ENABLED)
    VALUES('user', 'pass', true);

INSERT INTO USERS (USERNAME, PASSWORD, ENABLED)
    VALUES('admin', 'pass', true);


INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
    VALUES('user', 'ROLE_USER');

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
    VALUES('admin', 'ROLE_ADMIN');